"""change geometry type to multipolygon

Revision ID: 247a8de1c0ed
Revises: 80ff8c9cd354
Create Date: 2026-01-09 19:58:05.733566

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '247a8de1c0ed'
down_revision: Union[str, Sequence[str], None] = '80ff8c9cd354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'geom',
                    existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2,
                                                             from_text='ST_GeomFromEWKT', name='geometry',
                                                             nullable=False, _spatial_index_reflected=True),
                    type_=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2,
                                                     from_text='ST_GeomFromEWKT', name='geometry', nullable=False),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'geom',
                    existing_type=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2,
                                                             from_text='ST_GeomFromEWKT', name='geometry',
                                                             nullable=False),
                    type_=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2,
                                                     from_text='ST_GeomFromEWKT', name='geometry', nullable=False,
                                                     _spatial_index_reflected=True),
                    existing_nullable=False)
    # ### end Alembic commands ###
