"""initial migration

Revision ID: 80ff8c9cd354
Revises: 
Create Date: 2026-01-09 15:22:39.539391

"""
from typing import Sequence, Union

import geoalchemy2
import sqlmodel
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '80ff8c9cd354'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'buildings',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column(
            'geom',
            geoalchemy2.Geometry(
                geometry_type='POLYGON',
                srid=4326
            ),
            nullable=False
        ),
        sa.Column('data_source', sa.String(), nullable=False),
    )
    op.execute("DROP INDEX IF EXISTS idx_buildings_geom")
    op.create_index(
        'idx_buildings_geom',
        'buildings',
        ['geom'],
        postgresql_using='gist'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_buildings_geom', table_name='buildings', postgresql_using='gist')
    op.drop_table('buildings')
    # ### end Alembic commands ###
